site_name: YourControls Docs
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
plugins:
  - search:
      lang: en
  - awesome-pages
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/UqArVkXV99

copyright: Copyright &copy; 2022 YourControls
