site_name: YourControls Docs
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  palette:
    scheme: default
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - meta
  - md_in_html
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search:
      lang: en
  - awesome-pages

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/UqArVkXV99

copyright: Copyright &copy; 2022 YourControls
